### ISSUE TITLE
Left portion not visible in the certification section

### ISSUE THREAD

**Issue by RathoreSPaarth** [UtkarshChaurasia/My-Website#1]
A part of the timeline goes out of the screen in the certification section. Add some margin-left to it.
A damn good website though.

![image](https://user-images.githubusercontent.com/47487547/83936813-ac1a2c80-a7e4-11ea-91fa-e5f08c267d2d.png)

**Comment by UtkarshChaurasia** [comment]
Thanks for pointing out. I'll update it soon.
